version: '2.1'

services:
  base-server:
    build: .
    volumes:
      - .:/addressbook
      - /addressbook/node_modules

  database:
    image: postgres:10.5-alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=MY_S3KR37_DB$$
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    extends: base-server
    command: npm start
    environment:
      PORT: 3000
    ports:
      - 3000:3000

  test:
    extends: base-server
    command: npm test

  lint:
    extends: base-server
    command: npm run lint
