version: '2.1'

services:
  base-server:
    build: .
    volumes:
      - .:/addressbook
      - /addressbook/node_modules

  database:
    image: postgres:10.5-alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=MY_S3KR37_DB$$
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-database:
    extends: database
    environment:
      - POSTGRES_PASSWORD=addressbook

  server:
    extends: base-server
    command: npm start
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy

  debug-server:
    extends: base-server
    command: node --inspect=0.0.0.0 src/bin/server.js
    env_file: .env
    ports:
      - 3333:3333
      - 9229:9299
    depends_on:
      database:
        condition: service_healthy

  test:
    extends: base-server
    command: npm test
    environment:
      - NODE_ENV=test
      - JWT_SECRET=isthisastrongsecret
    depends_on:
        test-database:
          condition: service_healthy

  lint:
    extends: base-server
    command: npm run lint
