version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
        environment:
          NODE_ENV: "test"
      - image: postgres:10.5-alpine
        name: test-database

    working_directory: ~/addressbook

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies
      - run: npm install
      - run: npm run lint
      - run: npm test
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
