version: 2
jobs:
  build:
    docker:
      - image: node:8.10.12-alpine

    working_directory: ~/addressbook

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
        name: Install dependencies
        command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
        name: Run test suit
        command: npm test
