version: 2
jobs:
  tests:
    docker:
      - image: circleci/node:8.12
        environment:
          NODE_ENV: "test"
          JWT_SECRET: "strongsecret"
      - image: postgres:10.5-alpine
        name: test-database

    working_directory: ~/addressbook

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies
      - run:
          name: "Install dependencies"
          command: npm install
      - run:
          name: "Run linter"
          command: npm run lint
      - run:
          name: "Run database migrations"
          command: ./node_modules/.bin/ts-node ./node_modules/.bin/typeorm migration:run --config src/config/database.ts
      - run:
          name: "Run tests"
          command: npm test
      - run:
          name: "Build TypeScript"
          command: npm run build
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  deploy:
    working_directory: ~/addressbook
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: "Run migrations"
          command: |
            npx heroku run -a $HEROKU_APP_NAME './node_modules/.bin/ts-node ./node_modules/.bin/typeorm migration:run --config src/config/database.ts'
      - run:
          name: Deploy Tag to Heroku
          command: |
            git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $(git describe --tags):master

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - tests:
        filters:
          tags:
            only: /^v.*/
    - deploy:
        requires:
          - tests
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v([0-9]+).([0-9]+).([0-9]+).*$/
