version: 2
jobs:
  tests:
    docker:
      - image: circleci/node:8.12
        environment:
          NODE_ENV: "test"
          JWT_SECRET: "strongsecret"
      - image: postgres:10.5-alpine
        name: test-database

    working_directory: ~/addressbook

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies
      - run:
          name: "Install dependencies"
          command: npm install
      - run:
          name: "Run linter"
          command: npm run lint
      - run:
          name: "Run database migrations"
          command: ./node_modules/.bin/ts-node ./node_modules/.bin/typeorm migration:run --config src/config/database.ts
      - run:
          name: "Run tests"
          command: npm test
      - run:
          name: "Build TypeScript"
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
            - src/database/migrations
            - src/config/database.ts
            - src/config/index.ts
            - tsconfig.json
            - package.json
            - package-lock.json
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  deploy:
    working_directory: ~/addressbook
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Run migrations"
          command: |
            npm install ts-node typeorm typescript ramda pg --no-save
            ./node_modules/.bin/ts-node ./node_modules/.bin/typeorm migration:run --config src/config/database.ts
      - run:
          name: "Deploy to now.sh"
          command: |
            npm install now@12.1.8 --no-save
            ./node_modules/.bin/now --npm --public --build-env NODE_ENV=production -e DATABASE_URL -e DATABASE_NAME -e DATABASE_USERNAME -e DATABASE_PASSWORD -e JWT_SECRET -e FIREBASE_API_KEY -e FIREBASE_AUTH_DOMAIN -e FIREBASE_DATABASE_URL -e FIREBASE_PROJECT_ID -e FIREBASE_STORAGE_BUCKET -e FIREBASE_MESSAGING_SENDER_ID -e PORT=3000 --token $NOW_TOKEN

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - tests:
        filters:
          tags:
            only: /^v.*/
    - deploy:
        requires:
          - tests
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v([0-9]+).([0-9]+).([0-9]+).*$/
